name: Gh-Pages

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@master
        with:
          channel: 'master'
      - uses: erickzanardo/flutter-gh-pages@v3
    #    with:
    #      workingDir: web
